/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIndexRouteImport } from './routes/session.index'
import { Route as SessionReportRouteImport } from './routes/session.report'
import { Route as SessionFeedbackRouteImport } from './routes/session.feedback'
import { Route as SessionCallRouteImport } from './routes/session.call'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionReportRoute = SessionReportRouteImport.update({
  id: '/session/report',
  path: '/session/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionFeedbackRoute = SessionFeedbackRouteImport.update({
  id: '/session/feedback',
  path: '/session/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCallRoute = SessionCallRouteImport.update({
  id: '/session/call',
  path: '/session/call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/call': typeof SessionCallRoute
  '/session/feedback': typeof SessionFeedbackRoute
  '/session/report': typeof SessionReportRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/call': typeof SessionCallRoute
  '/session/feedback': typeof SessionFeedbackRoute
  '/session/report': typeof SessionReportRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/call': typeof SessionCallRoute
  '/session/feedback': typeof SessionFeedbackRoute
  '/session/report': typeof SessionReportRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session/call'
    | '/session/feedback'
    | '/session/report'
    | '/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/session/call'
    | '/session/feedback'
    | '/session/report'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/session/call'
    | '/session/feedback'
    | '/session/report'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionCallRoute: typeof SessionCallRoute
  SessionFeedbackRoute: typeof SessionFeedbackRoute
  SessionReportRoute: typeof SessionReportRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/report': {
      id: '/session/report'
      path: '/session/report'
      fullPath: '/session/report'
      preLoaderRoute: typeof SessionReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/feedback': {
      id: '/session/feedback'
      path: '/session/feedback'
      fullPath: '/session/feedback'
      preLoaderRoute: typeof SessionFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/call': {
      id: '/session/call'
      path: '/session/call'
      fullPath: '/session/call'
      preLoaderRoute: typeof SessionCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionCallRoute: SessionCallRoute,
  SessionFeedbackRoute: SessionFeedbackRoute,
  SessionReportRoute: SessionReportRoute,
  SessionIndexRoute: SessionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
